project_id = "rxnjjnsffahnxhhbpqxg"

[functions.analyze-ice-depth]
verify_jwt = false

[functions.get-weather]
verify_jwt = false

[functions.create-notification]
verify_jwt = false

[functions.send-ice-depth-report]
verify_jwt = false
